version: "1.0"
services:
  master_spark:
    image: pyfruit_spark
    ports:
      - 9090:9090
      - 7077:7077
    environment:
      - SPARK_LOCAL_IP=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=9090
    command: ./start-master.sh  
  worker1_spark:
    image: pyfruit_spark
    depends_on:
      - master_spark
    ports:
      - 9091:9091
      - 7000:7000
    volumes:
      - ../output:/app/output
      - ../data/fruits-360_dataset/fruits-360/Training:/app/data
      - /home/sparkuser/.aws:/root/.aws
    environment:
      - SPARK_MASTER=spark://ip_master:7077
      - SPARK_LOCAL_IP=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=9091
      #- SPARK_WORKER_CORES=4
      #- SPARK_WORKER_MEMORY=8G
      #- SPARK_DRIVER_MEMORY=8G
      #- SPARK_EXECUTOR_MEMORY=8G
    command: ./start-worker.sh  
  jupyter_client_spark:
    image: pyfruit_spark
    depends_on:
      - master_spark
      - worker1_spark
    ports:
      - 20002:20002
      - 6060:6060
      - 8888:8888
    volumes:
      - ../output:/app/output
      - ../data/fruits-360_dataset/fruits-360/Training:/app/data
      - ../notebooks:/app/notebooks
      - /home/sparkuser/.aws:/root/.aws
    environment:
      - JUPYTER_PORT=8888
      - JUPYTER_IP=0.0.0.0
      - PYFRUIT_MASTER=spark://ip_master:7077
      - PYFRUIT_LOCAL_IP=0.0.0.0
      - SPARK_LOCAL_IP=127.0.0.1
      - PYFRUIT_DRIVER_HOST=ip_driver
      - PYFRUIT_DRIVER_PORT=20002
      - PYFRUIT_BLOCKMANAGER_PORT=6060
    command: ./start-client_jupyter.sh