#!/bin/bash

echo "SPARK_LOCAL_IP="$SPARK_LOCAL_IP
echo "JUPYTER_IP="$JUPYTER_IP
echo "JUPYTER_PORT="$JUPYTER_PORT
echo "PYFRUIT_MASTER="$PYFRUIT_MASTER
echo "PYFRUIT_BLOCKMANAGER_PORT="$PYFRUIT_BLOCKMANAGER_PORT
echo "PYFRUIT_DRIVER_PORT="$PYFRUIT_DRIVER_PORT
echo "PYFRUIT_DRIVER_HOST="$PYFRUIT_DRIVER_HOST
echo "PYFRUIT_LOCAL_IP="$PYFRUIT_LOCAL_IP
echo "PYFRUIT_INPUT_PATH="$PYFRUIT_INPUT_PATH
echo "PYFRUIT_OUTPUT_PATH="$PYFRUIT_OUTPUT_PATH
echo "PYFRUIT_NC="$PYFRUIT_NC
echo "PYFRUIT_RESIZE="$PYFRUIT_RESIZE

jupyter notebook --port=$JUPYTER_PORT --allow-root --ip=$JUPYTER_IP